---
- name: installing and launching filebeat
  hosts: webservers
  become: yes
  tasks:

  - name: download metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.de
 
  - name: run package
    command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

  - name: drop in metricbeat.yml 
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable docker
    command: sudo metricbeat modules enable docker

  - name: setup metricbeat
    command: sudo metricbeat setup

  - name: start metric beat
    command: sudo service metricbeat start